#!/bin/sh

TEMP=$(mktemp -p $HOME/temp --suffix=.c)

cat <<'ENDHEAD' > "$TEMP"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <unistd.h>
#include <math.h>
#include <arpa/inet.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <inttypes.h>

#include <iostream>
#include <string>
#include <cstring>
#include <functional>
#include <array>
#include <vector>

int main(int argc, char** argv)
{
ENDHEAD

declare -a CFLAGS

CFLAGS="-std=gnu++11 "
CFLAGS="$(pkg-config --cflags eigen3) "
CFLAGS=-I"\"$PWD\" "

while [[ "$1" =~ ^- ]] || [[ -f "$1" ]]
do
	CFLAGS="$1"
	shift
done

if [[ "$#" -gt 0 ]]
then
	#echo $'\t'"$@" >> "$TEMP"
	while [[ "$#" -gt 0 ]]
	do
		echo $'\t'"$1" >> "$TEMP"
		shift
	done
else
	cat >> "$TEMP"
fi

cat <<'ENDTAIL' >> "$TEMP"
}
ENDTAIL

g++ "${CFLAGS[@]}" -o "${TEMP%%.c}" "$TEMP" -lm || exit 1

"${TEMP%%.c}"
EXITCODE=$?

rm -f "$TEMP" "${TEMP%%.c}"

exit $EXITCODE
