#!/usr/bin/python3
# -*- coding: utf8 -*-

import sys
import re
import math

from xml.etree import ElementTree
from pprint import pprint, pformat

if (len(sys.argv) < 2):
	print("Usage: %s <filename.brd>"%sys.argv[0])
	exit()

e = ElementTree.parse(sys.argv[1])
r = e.getroot()

descriptions = {}

for l in r.findall('./drawing/board/libraries/'):
	for p in l.findall('./packages/'):
		if (p.find('./description') is not None):
			descriptions["%s/%s"%(l.get('name'), p.get('name'))] = re.sub('<[^>]*>', '', p.find('./description').text.split('\n', 1)[0])

resultset = {}
attrs = []

for e in r.findall('./drawing/board/elements/'):
	if (e.attrib['library'] not in ('testpad',) and e.get('package') not in ('2PT_GND_TIE',)):
		attr_dict = {}
		attr_str  = ""
		for a in sorted(e.findall('./'), key=lambda n: str.lower(n.attrib['name'])):
			if ('value' in a.attrib):
				attr_dict[a.attrib['name']] = a.attrib['value']
				attr_str += "%s:%s\t" % (a.attrib['name'], a.attrib['value'])
				if (attrs.count(a.attrib['name']) == 0):
					attrs += [a.attrib['name']]
		key = ':'.join([e.attrib['package'], e.attrib['value'], attr_str]);
		#pprint(e.attrib)
		if (key not in resultset):
			resultset[key] = [e.attrib['value'], e.attrib['package'], descriptions.get("%s/%s" % (e.get('library'), e.get('package')), ''), attr_dict, [e.attrib['name']]]
		else:
			resultset[key][4] += [e.attrib['name']]

rows = []

attrl = sorted(attrs, key=str.lower)

print('"' + '","'.join(['Qty','Value','Package','Parts','Description'] + attrl) + '"')

for gn in sorted(resultset):
	rows += [gn]

for row in rows:
	#pprint(resultset[row])
	(value, package, description, attrs, namel) = resultset[row]
	qty = len(namel)
	names = ','.join(namel)
	attr = []
	for a in attrl:
		#print("%s:%s" % (a, attrs.get(a, '')))
		attr += [attrs.get(a, '')]
	print('"' + '","'.join([str(qty), value, package, names, description] + attr) + '"')
