#!/usr/bin/perl

# eagle-brd-dimension - emit board dimensions
#
# Copyright (C) 2017-2019 Michael Moon
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

use strict;

use XML::Simple;
use Data::Dumper;

if (@ARGV < 1) {
	print "Usage: eagle-brd-dimension <file.brd>\n";
	exit 0;
}

my @brd_offset;

my $fileprefix = $ARGV[0];
$fileprefix =~ s/\.brd$//;

my $xml = new XML::Simple;
my $data = $xml->XMLin($ARGV[0]);

for (@{$data->{drawing}->{board}->{plain}->{wire}}) {
	if ($_->{layer} == 20) {
		if (@brd_offset == 0) {
			@brd_offset = ($_->{x1}, $_->{y1}, $_->{x1}, $_->{y1});
		}
		$brd_offset[0] = $_->{x1} if $_->{x1} < $brd_offset[0];
		$brd_offset[1] = $_->{y1} if $_->{y1} < $brd_offset[1];
		$brd_offset[2] = $_->{x1} if $_->{x1} > $brd_offset[2];
		$brd_offset[3] = $_->{y1} if $_->{y1} > $brd_offset[3];
		$brd_offset[0] = $_->{x2} if $_->{x2} < $brd_offset[0];
		$brd_offset[1] = $_->{y2} if $_->{y2} < $brd_offset[1];
		$brd_offset[2] = $_->{x2} if $_->{x2} > $brd_offset[2];
		$brd_offset[3] = $_->{y2} if $_->{y2} > $brd_offset[3];
	}
}

for (@{$data->{drawing}->{board}->{plain}->{circle}}) {
	if ($_->{layer} == 20) {
		my ($x1, $y1, $x2, $y2) = ($_->{x} - $_->{radius}, $_->{y} - $_->{radius}, $_->{x} + $_->{radius}, $_->{y} + $_->{radius});
		if (@brd_offset == 0) {
			@brd_offset = ($x1, $y1, $x2, $y2);
		}
		$brd_offset[0] = $x1 if $x1 < $brd_offset[0];
		$brd_offset[1] = $y1 if $y1 < $brd_offset[1];
		$brd_offset[2] = $x1 if $x1 > $brd_offset[2];
		$brd_offset[3] = $y1 if $y1 > $brd_offset[3];
		$brd_offset[0] = $x2 if $x2 < $brd_offset[0];
		$brd_offset[1] = $y2 if $y2 < $brd_offset[1];
		$brd_offset[2] = $x2 if $x2 > $brd_offset[2];
		$brd_offset[3] = $y2 if $y2 > $brd_offset[3];
	}
}

printf "Board Dimension: %gmm x %gmm\n", ($brd_offset[2] - $brd_offset[0]), ($brd_offset[3] - $brd_offset[1]);
