#!/usr/bin/python3
# -*- coding: utf8 -*-

import sys
import re
import math

from xml.etree import ElementTree
from pprint import pprint, pformat

if (len(sys.argv) < 2):
	print("Usage: %s <filename.sch> <partname> [partname ...]"%sys.argv[0])
	exit()

parts = sys.argv[2:]

#pprint(parts)

e = ElementTree.parse(sys.argv[1])
r = e.getroot()

footprints = {}

rr = re.compile(r'.*?([A-Za-z][A-Za-z0-9_-]*)$')
unn = re.compile(r'N\$\d+|VCC|GND')

for net in r.findall('./drawing/schematic/sheets/sheet/nets/'):
	netname = net.get('name')
	if (unn.search(netname) is None):
		safenetname = re.sub(r'\!', 'n', netname)
		safenetname = re.sub(r'\W', 'x', safenetname)
		for seg in net.findall('./segment/'):
			if (seg.tag == 'pinref'):
				if (seg.get('part') in parts):
					part = seg.get('part')
					pin = seg.get('pin')
					pin = re.sub(r'\(.*?\)', '', pin)
					pin = re.sub(r'\[.*?\]', '', pin)
					#rematch = rr.match(pin)
					#if (rematch is not None):
						#pinname = rematch.groups()[0]
					pinname = re.sub(r'\!', 'n', pin)
					pinname = re.sub(r'\W', 'x', pinname)
					if (unn.search(pinname) is None):
						print("#define PIN_%-16s %s" % (part + "_" + safenetname, pinname))
