#!/usr/bin/python3
# -*- coding: utf8 -*-

import sys
import re
import math

from xml.etree import ElementTree
from pprint import pprint, pformat

if (len(sys.argv) < 2):
	print("Usage: %s <filename.brd>"%sys.argv[0])
	exit()

e = ElementTree.parse(sys.argv[1])
r = e.getroot()

layercount = 0

for l in r.findall('./drawing/layers/layer'):
	if (int(l.get('number')) <= 16):
		if (l.get('active') == 'yes'):
			layercount += 1

print(layercount)
