#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ]
then
	echo
	echo "Usage: $0 pattern%05d.png outputfile.mp4"
	echo
	exit 1
fi

ffmpeg -threads $(nproc) -f lavfi -i anullsrc -framerate 15 -i "$1" -c:v libvpx-vp9 -c:a libvorbis -r 15 -pix_fmt yuv420p -y -shortest "$2"
