#!/bin/bash

set -e

unset UNMOUNT

logger -t installkernel "installkernel '$0' '$1' '$2' '$3' '$4' '$5'"

#installkernel '/home/triffid/bin/installkernel' '5.1.7-gentoo-dorellan' 'arch/x86/boot/bzImage' 'System.map' '/boot' ''

KERNELVER="$1"
KERNELIMG="$2"
KERNELDEST="$4"

if ! [ -f "$KERNELIMG" ]
then
	echo "can't find $KERNELIMG"
	exit 1
fi

if [ "$EUID" -ne 0 ]
then
	sudo "$0" "$@"
	exit $?
fi

echo "*** Installing Modules"
make modules_install || exit 1

echo -n "*** Checking $KERNELDEST... "
if ! mountpoint -q "$KERNELDEST"
then
	UNMOUNT=1
	echo
	echo -n "*** Mounting $KERNELDEST... "
	mount "$KERNELDEST" || exit 1
fi
echo "OK"

echo -n "*** Copying $KERNELIMG -> $KERNELDEST/kernel-$KERNELVER... "
cp "$KERNELIMG" "$KERNELDEST/kernel-$KERNELVER" || exit 1
echo "OK"

if [ "$(readlink "$KERNELDEST/new")" != "kernel-$KERNELVER" ]
then
	echo -n "*** Updating Links... "
	mv -v "$KERNELDEST/new" "$KERNELDEST/old" || exit 1
	ln -sv "kernel-$KERNELVER" "$KERNELDEST/new" || exit 1
	echo "OK"
fi

if [ -n "$UNMOUNT" ]
then
	echo -n "*** Unmounting $KERNELDEST... "
	umount "$KERNELDEST" || exit 1
	echo "OK"
fi

echo
echo "Finished."
