#!/bin/bash

if [ -n "$1" ]
then
	curl --header 'Content-Type: application/json' --data-binary '{ "id": 1, "jsonrpc": "2.0", "method": "Player.SetSubtitle", "params": {"playerid": 1, "subtitle": "'"$1"'" } }' jeanelle.local:8080/jsonrpc; echo
else
	echo "Usage: kodi-sub <file or URL>"
	exit 1
fi
