#!/bin/bash

if [ -n "$1" ]
then
	curl --header 'Content-Type: application/json' --data-binary '{ "id": 1, "jsonrpc": "2.0", "method": "Player.Open", "params": {"item": { "file": "'"$1"'" } } }' jeanelle.local:8080/jsonrpc; echo
else
	echo "Usage: kodi-play <file or URL>"
	exit 1
fi
