#!/bin/bash

adb shell "service call connectivity 34 i32 1 s16 text"

sleep 1

adb shell "su - -c \"ip rule show | grep 'iif rndis0 lookup tun0' || ip rule add from all iif rndis0 lookup tun0 pref 17999; iptables -n -v -L natctrl_FORWARD | grep 'ACCEPT     all  --  rndis0 tun0' || iptables -I natctrl_FORWARD 4 -i rndis0 -o tun0 -j ACCEPT; iptables -n -v -L natctrl_FORWARD | grep 'ACCEPT     all  --  tun0   rndis0' || iptables -I natctrl_FORWARD 4 -i tun0 -o rndis0 -m state --state RELATED,ESTABLISHED -j ACCEPT\""
