#!/bin/bash

SCREENSHOT_DIR="$HOME/Screenshots"

NOW="$(date -Ins)"

DATETIME="$(date -d"${NOW}" +%Y%m%d-%H%M%S)"
DIR="$SCREENSHOT_DIR/$(date -d"${NOW}" +%Y/%Y%m)"
FILE="$DIR/screenshot-$DATETIME.png"

mkdir -p "$DIR" && ln -nfs "$DIR" "$SCREENSHOT_DIR/latest"

ffmpeg -f x11grab -i :0.0 -vframes 1 -update 1 "$FILE"

# mpv /usr/share/sounds/pop.wav
