#!/bin/bash

while [ -n "$1" ]
do
	for R in $(grep location /etc/portage/repos.conf/*.conf  | cut -d= -f2)
	do
		for P in "$R"/*-*/*$1*/
		do
			if [ -d $P ]; then
				. $P/*.ebuild 2>/dev/null
				P="$(rev <<< "$P" | cut -d/ -f 1-3 | rev)"
				P="${P%/}"
				REP="$(cat /etc/portage/repos.conf/*conf | perl -ne 'BEGIN { my $name=""; } chomp; /\[(.+)\]/ && do { $name = $1; }; m!'"$R"'$! && print "$name";')"
				echo -e "$P::${REP}\t"$DESCRIPTION"\t("$HOMEPAGE")" | \
					cgrep "\/$1[\\s:]" green                             | \
					cgrep "^\\S*\\b$1\\b" brown
			fi
		done
	done
	shift
done
