#!/bin/bash -x

SNAPSHOT_DIR="/snapshots/emerge"

btrfs subvolume show "$SNAPSHOT_DIR" || btrfs subvolume snapshot / "$SNAPSHOT_DIR" || exit 1;

mountpoint "$SNAPSHOT_DIR/dev" || mount --rbind --make-rslave /dev "$SNAPSHOT_DIR/dev" || exit 1;
mountpoint "$SNAPSHOT_DIR/sys" || mount --rbind --make-rslave /sys "$SNAPSHOT_DIR/sys" || exit 1;
mountpoint "$SNAPSHOT_DIR/proc" || mount --rbind --make-rslave /proc "$SNAPSHOT_DIR/proc" || exit 1;
mountpoint "$SNAPSHOT_DIR/mnt/storage" || mount --rbind --make-rslave /mnt/storage "$SNAPSHOT_DIR/mnt/storage" || exit 1;

[ -h "$SNAPSHOT_DIR/var/cache/packages" ] && ( rm "$SNAPSHOT_DIR/var/cache/packages" && mkdir "$SNAPSHOT_DIR/var/cache/packages"; )

echo 'EMERGE_DEFAULT_OPTS="${EMERGE_DEFAULT_OPTS} --buildpkg"' >> "$SNAPSHOT_DIR/etc/portage/make.conf"

CHROOT=1 chroot "$SNAPSHOT_DIR" /bin/bash

if ! lsof -n "$SNAPSHOT_DIR"
then
    umount -R "$SNAPSHOT_DIR/"{dev,sys,proc,mnt/storage} || exit 1
fi

echo
echo "Now run PKGDIR=$SNAPSHOT_DIR/var/cache/packages emerge -avtDUuk @world"
echo
